# -*- coding: utf-8 -*-

import re
import nltk
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import PorterStemmer
from nltk import word_tokenize


#from appos.appos import appos_dict
#from slangs.slangs import slangs_dict
#from stopwords.stopwords import stop_words_list
#from emoticons.emo import emo
from nltk.corpus import stopwords
stopword = stopwords.words('english')
lemmatizer=WordNetLemmatizer()


sb_stem = SnowballStemmer("english", ignore_stopwords=True)
pt_stem = PorterStemmer()

lmtzr = WordNetLemmatizer()

POS = ['JJ', 'JJR', 'JJS', 'RB', 'RBR', 'RBS', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']


def getPOS(words):
    posWords = []
    partsOfSpeech = nltk.pos_tag(words)
    for item in partsOfSpeech:
        word = item[0]
        posWords.append(item[1])
        if item[1] in POS:
            posWords.append(word)
        
    return partsOfSpeech


def weightCalculator(words):
    repeated_regex_pattern = re.compile(r'(.)\1+')
    weight = 0
    partsOfSpeech = nltk.pos_tag(words)
    for item in partsOfSpeech:
        word = item[0]
        result = re.match(repeated_regex_pattern, word)
        if result:
            if item[1] in POS:
                weight = weight + 1
        
        if word in slangs_dict:
            weight = weight + 1
            
        if word in emo:
            weight = weight + 1
        
    return weight
    

def appos_look_up(text):
    """
    Convert apostrophes word to original form
    Example: I don't know what is going on?  => I do not know what is going on? 
    Args:
        text (str): text 

    Returns:
        apposed (str) : text with converted apostrophes
    """
    try:
        words = text.split()
    except:
        print(text)
        return
    else:
        new_text = []
        for word in words:
            word_s = word.lower()
            if word_s in appos_dict:
                new_text.append(appos_dict[word_s])
            else:
                new_text.append(word)
        apposed = " ".join(new_text)
        return apposed


def remove_repeated_characters(text):
    """
    Remove repeated characters (>2) in words to max limit of 2
    Example: I am verrry happpyyy today => I am verry happyy today
    Args:
        text (str): text 

    Returns:
        clean_text (str): cleaned text with removed repeated chars
    """
    regex_pattern = re.compile(r'(.)\1+')
    clean_text = regex_pattern.sub(r'\1\1', text)
    return clean_text


def separate_digit_text(text):
    """
    Separate digit and words with space in text
    Example: I will be booking tickets for 2adults => I will be booking tickets for 2 adults   
    Args:
        text (str): text
    Returns:
        clean_text (str): cleaned text with separated digits and words
    """
    regex_patter = re.compile(r'([\d]+)([a-zA-Z]+)')
    clean_text = regex_patter.sub(r'\1 \2', text)
    return clean_text


def slang_look_up(text):
    """
    Replace slang word in text to their original form
    Example: hi, thanq so mch => hi, thank you so much
    Args:
        text (str): text
    Returns:
        slanged (str): cleaned text with replaced slang
    """
    words = text.split()
    new_text = []

    for word in words:
        word_s = word.lower()
        if word_s in slangs_dict:
            new_text.append(slangs_dict[word_s])
        else:
            new_text.append(word)
    slanged = " ".join(new_text)
    return slanged

            


def stem_text(text, stemmer='snowball'):
    """
    Convert words in text into their root form
    Example: I am playing in ground => I am play in ground 
    Args:
        text (str): text
        
    Returns:
        text_stem (str): cleaned text with replaced stem words
    """
    text = remove_inside_braces(text)
    tokens = word_tokenize(text)
    if stemmer == 'snowball':
        text_stem = " ".join([sb_stem.stem(w) for w in tokens])
    else:
        text_stem = " ".join([pt_stem.stem(w) for w in tokens])
    
    return text_stem


def lemmatize_text(text):    
#    text = remove_inside_braces(text)
    tokens = word_tokenize(text)
    text_stem = " ".join([lemmatizer.lemmatize(word) for word in tokens])
    
    return text_stem



def remove_single_char_word(text):
    """
    Remove single character word from text
    Example: I am in a home for 2 years => am in home for years 
    Args:
        text (str): text
         
    Returns:
        (str): text with single char removed
    """
    words = text.split()
    filter_words = [word for word in words if len(word) > 1]
    return " ".join(filter_words)


def remove_punctuations(text):
    """
    Removed special characters from text
    Example: he: I am going. are you coming? => he I am going. are you coming
   
    Args:
        text (str): text
   
    Returns:
        clean_text (str): cleaned text with removed special characters
    """
    regex_pattern = re.compile(r'[\,+\:\?\!\"\(\)!\'\.\%\[\]]+')
    clean_text = regex_pattern.sub(r' ', text)
    clean_text = clean_text.replace('-', '')
    return clean_text


def remove_extra_space(text):
    """
    Remove extra white spaces space from text
    Example: hey are   you coming. ? => he are you coming. ?
    Args:
        text (str): text
    Returns:
        clean_text (str): clean text with removed extra white spaces
    """
    clean_text = ' '.join(text.strip().split())
    return clean_text


def replace_digits_with_char(text, replace_char='d'):
    """
    Replace digits to `replace_char`
    Example: I will be there on 22 april. => I will be there on dd april.
    Args:
        text (str): text
        replace_char (str): character with which digit has to be replaced
    Returns:
        clean_text (str): clean text with replaced char for digits
    """
    regex_pattern = re.compile(r'[0-9]')
    clean_text = regex_pattern.sub(replace_char, text)
    return clean_text


def emoticons_look_up(text):
    """
    Remove emoticons from text and returns list of emotions present in text
    Example: Sure, you are welcome :) => Sure, you are welcome.
    Args:
        text (str): text
    Returns:
        text (str): text with removed emoticons sign
        emolist (list) : list of emotions from text
    """

    words = text.split()
    emolist = []
    for word in words:
        if word in emo:
            emolist.append(str(emo[word]))
            text = text.replace(word," ")
    return text, emolist


def remove_url(text):
    """
    Remove urls from text
    Example: link to latest cricket score. https://xyz.com/a/b => link to latest cricket score.
    Args:
        text (str): text
    Returns:
        text (str): text with removed urls
    """

    urlfree = []
    try:
        for word in text.split():
            if not word.startswith("www"):
                urlfree.append(word)
            elif not word.startswith("http"):
                urlfree.append(word)
            elif not word.endswith(".html"):
                urlfree.append(word)
        urlfree = " ".join(urlfree)
    
        urls = re.finditer(r'http[\w]*:\/\/[\w]*\.?[\w-]+\.+[\w]+[\/\w]+', urlfree)
        for i in urls:
            urlfree = re.sub(i.group().strip(), '', urlfree)
        return urlfree
    except:
        return


def remove_alphanumerics(text):
    """
    Remove alphanumeric words from text
    Example: hello man whatsup123 => hello man
    Args:
        text (str): text
    Returns:
        text (str): text with removed alphanumeric words
    """
    txt = []
    try:
        for each in text.split():
            if not any(x in each.lower() for x in "0123456789"):
                txt.append(each)
        txtsent = " ".join(txt)
        return txtsent
    except:
        return

def remove_words_start_with(text, starts_with_char):
    """
    Remove words start with character `starts_with_char`
    Example: dhoni rocks with last ball six #dhoni #six => dhoni rocks with last ball six (start_char_with='#')
    Args:
        text (str): text
        starts_with_char (str): starting characters of word, which to be removed from text

    Returns:
        text (str): text with removed words start with given chars
    """
    urls = re.finditer(starts_with_char + r'[A-Za-z0-9\w]*', text)
    for i in urls:
        text = re.sub(i.group().strip(), '', text)
    return text.strip()

# =============================================================================
# def remove_stop_words(text, stop_words=stop_words_list):
#     """
#     This function removes stop words from text
#     Example: I am very excited for today's football match => very excited today's football match
#     Params
#         text (str) :text on which processing needs to done
#         stop_words (list) : stop words which needs to be removed
#     Returns
#         text(str): text after stop words removal
#     """
#     stop_words = set(stop_words)
#     split_list = text.split(" ")
#     split_list = [word for word in split_list if word not in stop_words]
#     return " ".join(split_list)
# =============================================================================

def remove_key_words(text):
   
    
    key_words = set(['workstress', 'workLoad', 'JobStress', 'work', 'Work', 'work+stress', 'worklife+stress', 'job+overloaded', 'job+stress', 'office','Click', 'Did', 'officestress', 'office+stress', 'WorkHard + stress', 'The', 'You', 'see', 'Let', 'RT','eorkstress', 'thi', 'wa', 'it', 'It', 'wa', 'Begin', 'workload', 'stress', 'rt', 'job', 'let', 'click'])
    split_list = text.split(" ")
    split_list = [word for word in split_list if word.strip() not in key_words]
    return " ".join(split_list)


def to_lower(text):
    """
    Converting text to lower case as in, converting "Hello" to  "hello" or "HELLO" to "hello".
    """
    return ' '.join([w.lower() for w in word_tokenize(text)])

def removeStopWords(text):
    word_tokens = nltk.word_tokenize(text)
    removing_stopwords = [word for word in word_tokens if word not in stopword]
    return ' '.join(removing_stopwords)

def removeShortWords(text):
    word_tokens = nltk.word_tokenize(text)
    removing_stopwords = [word for word in word_tokens if len(word) > 2]
    return ' '.join(removing_stopwords)




appos_dict = {
    "can't": "cannot",
    "cant": "cannot",
    "aren't": "are not",
    "arent": "are not",
    "couldn't": "could not",
    "couldnt": "could not",
    "doesn't": "does not",
    "doesnt": "does not",
    "don't": "do not",
    "dont": "do not",
    "hadn't": "had not",
    "hadnt": "had not",
    "hasn't": "has not",
    "hasnt": "has not",
    "haven't": "have not",
    "havent": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "i'd": "I would",
    "i'll": "I will",
    "i'm": "I am",
    "im": "I am",
    "isn't": "is not",
    "isnt": "is not",
    "it's": "it is",
    "it'll": "it will",
    "i've": "I have",
    "let's": "let us",
    "mightn't": "might not",
    "mightnt": "might not",
    "mustn't": "must not",
    "mustnt": "must not",
    "shan't": "shall not",
    "she'd": "she would",
    "she'll": "she will",
    "she's": "she is",
    "shouldn't": "should not",
    "shouldnt": "should not",
    "that's": "that is",
    "thats": "that is",
    "there's": "there is",
    "they'd": "they would",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "we'd": "we would",
    "we're": "we are",
    "weren't": "were not",
    "we've": "we have",
    "what'll": "what will",
    "what're": "what are",
    "what's": "what is",
    "whats": "what is",
    "what've": "what have",
    "where's": "where is",
    "who'd": "who would",
    "who'll": "who will",
    "who're": "who are",
    "who's": "who is",
    "who've": "who have",
    "won't": "will not",
    "wont": "will not",
    "wouldn't": "would not",
    "wouldnt": "would not",
    "you'd": "you would",
    "you'll": "you will",
    "you're": "you are",
    "you've": "you have",
    "wasn't": "was not",
    "wasnt": "was not",
    "we'll": "will",
    "didn't": "did not",
    "didnt": "did not",
    "'s" : "is"
}


slangs_dict = {
    'awsm': 'awesome',
    "aamof": "as a matter of fact",
    "abt": "about",
    "abt2": "about to",
    "ac": "air conditioning",
    "ace": "solo winner",
    "ack": "acknowledged",
    "admin": "administrator",
    "thr": "there",
    "frm": "from",
    "aggro": "aggression",
    "agl": "angel",
    "dob": "date of birth",
    "ai": "artificial intelligence",
    "aiic": "as if i care",
    "aka": "also known as",
    "alap": "as long as possible",
    "alol": "actually laughing out loud",
    "ama": "ask me anything",
    "amap": "as much as possible",
    "amazn": "amazing",
    "ammo": "ammunition",
    "ams": "ask me something",
    "anon": "anonymous",
    "asap": "as soon as possible",
    "asat": "as simple as that",
    "awks": "awkward",
    "awl": "always with love",
    "ayk": "as you know",
    "azm": "awesome",
    "b": "be",
    "b&w": "black and white",
    "b-day": "birthday",
    "bday": "birthday",
    "bcoz": "because",
    "bcos": "because",
    "bcz": "because",
    "bf": "boyfriend",
    "btw": "between",
    "b4": "before",
    "bai": "bye",
    "bb": "bye bye",
    "bc": "abuse",
    "mc": "abuse",
    "bcc": "blind carbon copy",
    "bff": "best friends forever",
    "biz": "business",
    "bk": "back",
    "bo": "back off",
    "bro": "brother",
    "btwn": "between",
    "c": "see",
    "char": "character",
    "combo": "combination",
    "cu": "see you",
    "cu2": "see you too",
    "cu2mr": "see you tomorrow",
    "cya": "see ya",
    "cyal8r": "see you later",
    "cyb": "call you back",
    "cye": "check your e-mail",
    "cyf": "check your facebook",
    "cyfb": "check your facebook",
    "cyl": "catch ya later",
    "cym": "check your myspace",
    "cyo": "see you online",
    "d8": "date",
    "da": "the",
    "dece": "decent",
    "ded": "dead",
    "dept": "department",
    "dis": "this",
    "ditto": "same",
    "diva": "rude woman",
    "dk": "don't know",
    "dlm": "don't leave me",
    "dm": "direct message",
    "dnd": "do not disturb",
    "dno": "don't know",
    "dnt": "don't",
    "e1": "everyone",
    "eg": "for example",
    "emc2": "genius",
    "emo": "emotional",
    "enuf": "enough",
    "eod": "end of discussion",
    "eof": "end of file",
    "eom": "end of message",
    "eta": "estimated time of arrival",
    "every1": "everyone",
    "evs": "whatever",
    "exp": "experience",
    "f": "female",
    "f2f": "face to face",
    "f2p": "free to play",
    "f2t": "free to talk",
    "f9": "fine",
    "fab": "fabulous",
    "fail": "failure",
    "faq": "frequently asked questions",
    "fav": "favorite",
    "fave": "favorite",
    "favs": "favorites",
    "fb": "facebook",
    "fbc": "facebook chat",
    "fbf": "facebook friend",
    "fml": "family",
    "fn": "fine",
    "fo": "freaking out",
    "fri": "friday",
    "frnd": "friend",
    "fu": "fuck you",
    "fugly": "fucking ugly",
    "gf": "girlfriend",
    "g1": "good one",
    "g2b": "going to bed",
    "g2cu": "good to see you",
    "g2g": "good to go",
    "g4i": "go for it",
    "g4n": "good for nothing",
    "g4u": "good for you",
    "g9": "goodnight",
    "ga": "go ahead",
    "ge": "good evening",
    "gl": "good luck",
    "gm": "good morning",
    "gn": "goodnight",
    "gonna": "going to",
    "goon": "idiot",
    "gorge": "gorgeous",
    "gr8": "great",
    "grats": "congratulations",
    "gratz": "congratulations",
    "grl": "girl",
    "gt2t": "got time to talk",
    "gtg": "good to go",
    "gud": "good",
    "gv": "give",
    "gvn": "given",
    "gw": "good work",
    "h/o": "hold on",
    "h/p": "hold please",
    "h/t": "hat tip",
    "h/u": "hook up",
    "h2cus": "hope to see you soon",
    "h4u": "hot for you",
    "h4x0r": "hacker",
    "h4x0rz": "hackers",
    "h8": "hate",
    "h8r": "hater",
    "h8t": "hate",
    "ha": "hello again",
    "haha": "laughing",
    "hai": "hi",
    "hak": "hugs and kisses",
    "han": "how about now?",
    "hav": "have",
    "hax": "hacks",
    "haxor": "hacker",
    "hay": "how are you",
    "hb2u": "happy birthday to you",
    "hbbd": "happy belated birthday",
    "hbd": "happy birthday",
    "hc": "how cool",
    "hcit": "how cool is that",
    "hehe": "laughing",
    "hf": "have fun",
    "hi5": "high five",
    "hig": "how's it going?",
    "hih": "hope it helps",
    "ho": "hold on",
    "hoc": "house of cards",
    "hof": "hall of fame",
    "holla": "holler",
    "hom": "hit or miss",
    "hood": "neighborhood",
    "hoops": "basketball",
    "hottie": "attractive person",
    "hr": "human resources",
    "hru": "how are you",
    "hry": "hurry",
    "hubby": "husband",
    "hwk": "homework",
    "hwp": "height weight proportionate",
    "hwu": "hey, what's up?",
    "hxc": "hardcore",
    "h^": "hook up",
    "i8": "i ate",
    "i8u": "i hate you",
    "ia": "i agree",
    "iab": "in a bit",
    "iac": "in any case",
    "iad": "it all depends",
    "iae": "in any event",
    "iag": "it's all good",
    "iagw": "in a good way",
    "iail": "i am in love",
    "iam": "in a minute",
    "ic": "i see",
    "id10t": "idiot",
    "idc": "i don't care",
    "idd": "indeed",
    "idi": "i doubt it",
    "idk": "i don't know",
    "idky": "i don't know why",
    "idmb": "i'll do my best",
    "idn": "i don't know",
    "idnk": "i do not know",
    "idr": "i don't remember",
    "idt": "i don't think",
    "idts": "i don't think so",
    "idtt": "i'll drink to that",
    "idu": "i don't understand",
    "ie": "that is",
    "ig2p": "i got to pee",
    "iggy": "ignored",
    "ight": "alright",
    "igi": "i get it",
    "ign": "in-game name",
    "igtp": "i get the point",
    "ih8u": "i hate you",
    "ihu": "i hate you",
    "ihy": "i hate you",
    "ii": "i'm impressed",
    "iiok": "if i only knew",
    "iir": "if i remember",
    "iirc": "if i remember correctly",
    "iit": "i'm impressed too",
    "iiuc": "if i understand correctly",
    "ik": "i know",
    "ikhyf": "i know how you feel",
    "ikr": "i know, right?",
    "ikwum": "i know what you mean",
    "ikwym": "i know what you mean",
    "ikyd": "i know you did",
    "ilu": "i like you",
    "ilu2": "i love you too",
    "ilub": "i love you baby",
    "ilyk": "i'll let you know",
    "ilyl": "i love you lots",
    "ilysm": "i love you so much",
    "ima": "i'm",
    "imma": "i'm gonna",
    "imo": "in my opinion",
    "imy": "i miss you",
    "inb4": "in before",
    "inc": "incoming",
    "indie": "independent",
    "info": "information",
    "init": "initialize",
    "ipo": "initial public offering",
    "ir": "in room",
    "ir8": "irate",
    "irdk": "i really don't know",
    "irl": "in real life",
    "iyo": "in your opinion",
    "iyq": "i like you",
    "j/k": "just kidding",
    "j/p": "just playing",
    "j/w": "just wondering",
    "j2lyk": "just to let you know",
    "j4f": "just for fun",
    "j4g": "just for grins",
    "jas": "just a second",
    "jb/c": "just because",
    "joshing": "joking",
    "k": "ok",
    "k3u": "i love you",
    "kappa": "sarcasm",
    "kek": "korean laugh",
    "keke": "korean laugh",
    "kewl": "cool",
    "kewt": "cute",
    "kfc": "kentucky fried chicken",
    "kgo": "ok, go",
    "kik": "laughing out loud",
    "kinda": "kind of",
    "kk": "ok",
    "kl": "kool",
    "km": "kiss me",
    "kma": "kiss my ass",
    "knp": "ok, no problem",
    "kw": "know",
    "kwl": "cool",
    "l2m": "listening to music",
    "l2p": "learn to play",
    "l33t": "leet",
    "l8": "late",
    "l8er": "later",
    "l8r": "later",
    "la": "laughing a lot",
    "laf": "laugh",
    "laffing": "laughing",
    "lafs": "love at first sight",
    "lam": "leave a message",
    "lamer": "lame person",
    "legit": "legitimate",
    "lemeno": "let me know",
    "lil": "little",
    "lk": "like",
    "llol": "literally laughing out loud",
    "lmho": "laughing my head off",
    "loi": "laughing on the inside",
    "lola": "love often, laugh a lot",
    "lolol": "lots of laugh out louds",
    "lolz": "laugh out louds",
    "ltr": "later",
    "lulz": "lol",
    "luv": "love",
    "luzr": "loser",
    "lv": "love",
    "ly": "love ya",
    "lya": "love you always",
    "lyk": "let you know",
    "lyn": "lying",
    "lysm": "love you so much",
    "m": "male",
    "mcd": "mcdonald's",
    "mcds": "mcdonald's",
    "md@u": "mad at you",
    "me2": "me too",
    "meh": "whatever",
    "mf": "mother fucker",
    "mfb": "mother fucking bitch",
    "mgmt": "management",
    "mid": "middle",
    "mil": "mother-in-law",
    "min": "minute",
    "mins": "minutes",
    "mk": "okay",
    "mkay": "ok",
    "mmk": "ok",
    "mms": "multimedia messaging service",
    "mng": "manage",
    "mngr": "manager",
    "mod": "modification",
    "mofo": "mother fucking",
    "mojo": "attractive talent",
    "moss": "chill",
    "ms": "miss",
    "msg": "message",
    "mtg": "meeting",
    "mth": "month",
    "mu": "miss you",
    "mu@": "meet you at",
    "muah": "kiss",
    "mula": "money",
    "mwa": "kiss",
    "mwah": "kiss",
    "n/m": "nevermind",
    "n/m/h": "nothing much here",
    "n/r": "no reserve",
    "n00b": "newbie",
    "n1": "nice one",
    "n1c": "no one cares",
    "n2m": "not too much",
    "n2mh": "not too much here",
    "n2w": "not to worry",
    "n64": "nintendo 64",
    "n8kd": "naked",
    "nac": "not a chance",
    "nah": "no",
    "nal": "nationality",
    "narc": "tattle tale",
    "nark": "informant",
    "naw": "no",
    "nb": "not bad",
    "nbd": "no big deal",
    "nbjf": "no brag, just fact",
    "nd": "and",
    "ne": "any",
    "ne1": "anyone",
    "ne1er": "anyone here",
    "neh": "no",
    "nemore": "anymore",
    "neva": "never",
    "neway": "anyway",
    "newaze": "anyways",
    "newb": "newbie",
    "nite": "night",
    "nn2r": "no need to reply",
    "nnito": "not necessarily in that order",
    "nnto": "no need to open",
    "nntr": "no need to reply",
    "no1": "no one",
    "noob": "newbie",
    "nooblet": "young newbie",
    "nooblord": "ultimate newbie",
    "notch": "minecraft creator",
    "nottie": "unattractive person",
    "np": "no problem",
    "nub": "newbie",
    "nuff": "enough",
    "nufn": "nothing",
    "num": "tasty",
    "nvm": "nevermind",
    "nvr": "never",
    "nvrm": "nevermind",
    "nw": "no way",
    "nxt": "next",
    "o4u": "only for you",
    "obtw": "oh, by the way",
    "obv": "obviously",
    "obvi": "obviously",
    "oc": "of course",
    "ohemgee": "oh my gosh",
    "oic": "oh, i see",
    "oicn": "oh, i see now",
    "oiy": "hi",
    "omg": "oh my god",
    "onl": "online",
    "onoz": "oh no",
    "orly": "oh really",
    "otay": "okay",
    "otw": "on the way",
    "outta": "out of",
    "ovie": "overlord",
    "ownage": "completely owned",
    "p/d": "per day",
    "p/m": "per month",
    "p/y": "per year",
    "p911": "parent alert!",
    "p@h": "parents at home",
    "pc": "personal computer",
    "pda": "public display of affection",
    "pic": "picture",
    "pj": "poor joke",
    "pl8": "plate",
    "pld": "played",
    "pls": "please",
    "plz": "please",
    "plzrd": "please read",
    "pov": "point of view",
    "ppl": "people",
    "ppp": "peace",
    "prof": "professor",
    "prolly": "probably",
    "promo": "promotion",
    "props": "recognition",
    "prot": "protection",
    "prvt": "private",
    "ps": "postscript",
    "ps2": "playstation 2",
    "ps3": "playstation 3",
    "psa": "public service announcement",
    "psog": "pure stroke of genius",
    "psp": "playstation portable",
    "ptm": "please tell me",
    "pwd": "password",
    "psd": "password",
    "pswd": "password",
    "pwnd": "owned",
    "pwned": "owned",
    "pwnt": "owned",
    "q4u": "question for you",
    "qfe": "quoted for emphasis",
    "qft": "quoted for truth",
    "qq": "quick question",
    "qqn": "looking",
    "qrg": "quick reference guide",
    "qt": "cutie",
    "qtpi": "cutie pie",
    "r": "are",
    "r8": "rate",
    "rdy": "ready",
    "re": "replay",
    "rehi": "hi again",
    "rents": "parents",
    "rep": "reputation",
    "resq": "rescue",
    "rgd": "regard",
    "rgds": "regards",
    "ridic": "ridiculous",
    "rip": "rest in peace",
    "rl": "real life",
    "rlrt": "real life retweet",
    "rly": "really",
    "rm": "room",
    "rn": "run",
    "rnt": "aren't",
    "rof": "laughing",
    "rofl": "laughing",
    "roflmao": "laughing",
    "roflol": "laughing out loud",
    "rolf": "laughing",
    "ru": "are you",
    "ruc": "are you coming?",
    "rut": "are you there?",
    "rx": "prescription",
    "s/o": "sold out",
    "s/u": "shut up",
    "s/w": "software",
    "s2r": "send to receive",
    "s2s": "sorry to say",
    "s2u": "same to you",
    "samzd": "still amazed",
    "sd": "sweet dreams",
    "sec": "second",
    "sho": "sure",
    "sh^": "shut up",
    "siul8r": "see you later",
    "siv": "bad goaltender",
    "sk8": "skate",
    "sk8r": "skater",
    "sly": "still love you",
    "smf": "so much fun",
    "smooch": "kiss",
    "sorta": "sort of",
    "spec": "specialization",
    "spk": "speak",
    "spkr": "speaker",
    "srry": "sorry",
    "srs": "serious",
    "srsly": "seriously",
    "sry": "sorry",
    "stpd": "stupid",
    "str": "strength",
    "str8": "straight",
    "sup": "what's up",
    "syl": "see you later",
    "sync": "synchronize",
    "t2go": "time to go",
    "t2m": "talk to me",
    "t2u": "talk to you",
    "t2ul": "talk to you later",
    "t2ul8er": "talk to you later",
    "t2ul8r": "talk to you later",
    "t4lmk": "thanks for letting me know",
    "t4p": "thanks for posting",
    "t4t": "thanks for trade",
    "tc": "take care",
    "teh": "the",
    "teme": "tell me",
    "tg": "thank goodness",
    "thnq": "thank you",
    "tho": "though",
    "thru": "through",
    "tht": "that",
    "thx": "thanks",
    "tl": "tell",
    "tlk": "talk",
    "tlkin": "talking",
    "tlking": "talking",
    "tomoz": "tomorrow",
    "tq": "thank you",
    "tqvm": "thank you very much",
    "tru": "true",
    "ttl": "talk to you later",
    "ttly": "totally",
    "ttul": "talk to you later",
    "tty": "talk to you",
    "tu": "thank you",
    "tude": "attitude",
    "tx": "thanks",
    "txt": "text",
    "txtin": "texting",
    "ty": "thank you",
    "tyfa": "thank you for asking",
    "tyl": "thank you lord",
    "tym": "thank you much",
    "tyt": "take your time",
    "tyvm": "thank you very much",
    "u": "you",
    "u-ok": "you ok?",
    "u/l": "upload",
    "u2": "you too",
    "u2u": "up to you",
    "uok": "you ok?",
    "ur": "your",
    "ut": "you there?",
    "veggies": "vegetables",
    "vry": "very",
    "vs": "versus",
    "w/": "with",
    "w/b": "welcome back",
    "w/e": "whatever",
    "w/o": "without",
    "w2f": "way too funny",
    "w2g": "way to go",
    "w2k": "windows 2000",
    "w4u": "wait for you",
    "w8": "wait",
    "w84m": "wait for me",
    "w8am": "wait a minute",
    "w8ing": "waiting",
    "w8n": "waiting",
    "wa": "what",
    "waa": "crying",
    "wack": "strange",
    "wan2": "want to",
    "wannabe": "want to be",
    "wat": "what",
    "watev": "whatever",
    "watevs": "whatever",
    "wlcm": "welcome",
    "wha": "what",
    "whipped": "tired",
    "wht": "what",
    "wk": "week",
    "wknd": "weekend",
    "wtf": "what the fuck",
    "wtg": "way to go",
    "wup": "what's up?",
    "ya": "yes",
    "yeap": "yes",
    "yep": "yes",
    "yepperz": "yes",
    "yesh": "yes",
    "yo": "hi",
    "yr": "your",
    "yrs": "years",
    "yt": "you there?",
    "yt?": "you there?",
    "yup": "yes",
    "yupz": "ok",
    "zzz": "sleeping",
}


emo = {
"O(<>'<>)O ":0,
'==(:-)=' :0,
'=|:)>' :0,
'=|:-)' :0,
'=|:-)=' :0,
'=(_)' :-1,
':%)' :0,
'?:^[]' :0,
':%)%' :-1,
'):=' :0,
'/.#(' :0,
':-=)' :1,
'8-[' :-1,
'(ap)' :0,
"-|--' ":0,
':-o' :-1,
'c|B-)' :0,
'(.V.)' :0,
'(8>/--<' :0,
'OOOOOO' :0,
'\^/' :1,
'(<>..<>)' :0,
'::-)' :1,
'>(::O>' :0,
'>-)' :1,
'<0>..<0>' :0,
'((-(-.-)-))' :1,
':8)' :1,
'>*^,^,^~~~' :-1,
'0=)' :1,
'^j^' :1,
'O:)' :1,
'(a)' :1,
'O:-)' :1,
'O-)' :1,
'0-)<' :1,
'0;)' :1,
'0:)' :1,
'0*-)' :1,
'():)' :1,
'J^' :1,
'(angel)' :1,
':-t' :-1,
':-||' :-1,
'X-(' :-1,
'X(' :-1,
':-@' :-1,
':@' :-1,
':(' :-1,
'>-(' :-1,
'D<' :-1,
'>:(' :-1,
'>:-(' :-1,
'-_-+' :-1,
':-Z' :-1,
'(((p(>o<)q)))' :-1,
':=@' :-1,
'x=(' :-1,
'(angry)' :-1,
'>(' :-1,
'(_)' :-1,
'(#_)' :-1,
'()' :-1,
'>:-o' :-1,
'>:-0' :-1,
'||' :-1,
'^w^' :1,
'-_-;' :0,
"|_|' ":0,
'^^;' :0,
'@_@' :-1,
'' :-1,
'>_<*' :-1,
':/' :-1,
'>:-(' :-1,
'(_")' :-1,
':42:' :0,
"-o,,o,,o' ":0,
'>:' :0,
'()' :1,
'm(_)m' :0,
'm(T-T)m' :0,
'=D>' :1,
'(^^)//' :1,
'()' :1,
'0-+' :0,
'>A<' :1,
"<')))~ ":0,
',,\(o3o)/,,' :0,
'>--->>' :0,
'<---<<<' :0,
':arrow:' :0,
'(B-I=' :-1,
'(_)' :-1,
'(_!l)' :-1,
'(_)' :-1,
'(>)' :-1,
'<|-)' :0,
'|-I' :0,
':D' : 1,
'(0)-<-<' :0,
'~X(' :1,
'X:-)' :0,
'(au)' :0,
':S' :-1,
'o.e' :-1,
':=8)' :0,
'~:0' :0,
'~O><' :0,
'[{-_-}]' :0,
'~:O' :0,
'X:-)' :-1,
'_' :-1,
'=.=' :-1,
'C:-|' :1,
'(8-)' :1,
':-)-S=~' :0,
'o~' :0,
'((' :0,
'(bandit)' :0,
'(headbang)' :0,
'(banghead)' :0,
"~'v ":0,
':-%' :0,
'~~~' :0,
':-C~' :0,
'8o|' :0,
':-E' :0,
'>--<(:p' :0,
'd:-)' :0,
'd:-p' :0,
'q:-)' :0,
'^v^' :0,
'(^+.+^)' :0,
'\()/' :0,
'B-|' :0,
'B-)' :1,
';;)' :1,
'_' :-1,
'()' :-1,
'(brb)' :1,
"('')-.-('') ":0,
"\'''\(*.*)/'''/ ":0,
'O_______' :0,
'(""\(O_O)/"")' :0,
'(()' :0,
'(())' :0,
'(())' :0,
'()' :0,
"(''')-.-(''') ":0,
'' :0,
'(())' :0,
'' :0,
'()' :0,
':)#' :1,
'(:-{~' :0,
':-)}' :0,
'b-(' :0,
'%+|' :-1,
'(#_#)' :-1,
'(*@_#)' :-1,
'(O_.)' :-1,
'(=_)' :-1,
'0___' :0,
'X:-|' :0,
'~(,)~' :0,
':bz' :0,
'(b)' :0,
'___' :0,
'|__|/' :0,
'[%]D' :0,
'(beer)' :0,
'(bricklayers)' :0,
'(_)3' :0,
'm(-_-)m' :-1,
'::::[||]::::' :0,
'_' :0,
'OTL' :-1,
'' :1,
'&:-o-8-<' :0,
'#:o+=' :0,
'o_0' :-1,
'(".")' :-1,
'|_______|' :0,
':-D' :1,
':grin:' :1,
':=D' :1,
'(laugh)' :1,
'()' :1,
'>:D<' :0,
'8|___)' :0,
':-(|)' :0,
'(|X0||)' :0,
'o=>' :-1,
'(*v*)' :0,
'<;' :0,
'=W' :0,
'~:<>' :0,
'/"' :0,
'(8>)<' :0,
'~O~' :0,
'll' :0,
'0>' :0,
'{v}' :0,
'(`)' :0,
'()' :0,
'' :0,
'()' :0,
'(^)' :0,
'(cake)' :0,
'*<:)' :1,
'<>:-)' :0,
':*x' :-1,
':-s' :0,
'(:-D' :-1,
'!-(' :0,
'?-(' :0,
'(bah)' :0,
'8^P' :-1,
'|-(' :-1,
'#-)' :-1,
'^^' :1,
':c)' :1,
'<^^*>' :1,
'(@)/(@)' :-1,
'(O)' :-1,
'(--)*' :0,
'*8=(:' :0,
':-">' :-1,
":,') ":-1,
'=">' :-1,
':-*>' :-1,
'=^}' :-1,
':")' :-1,
'=^_^=' :-1,
'=<_<=' :-1,
':*-)' :-1,
':">' :-1,
':8}' :-1,
'(blush)' :-1,
':=$' :-1,
'>//<' :-1,
'c-----7' :0,
'@=' :-1,
'(_)' :0,
'()' :0,
':-o' :-1,
':/' :-1,
'(-_-)' :-1,
'\-o' :-1,
':-o' :-1,
':z' :-1,
'(_)' :0,
'(/-_)/D>' :0,
':-)8' :1,
':-)x' :1,
'orz' :1,
'(bow)' :1,
'(||)' :0,
'===O____iii' :0,
'_____O___III' :0,
'____o/|||' :0,
'o(^_-)O' :0,
'O??' :0,
'(z)' :0,
'(:-)' :1,
':-)^<' :0,
':-#' :-1,
':-{#}' :-1,
'=#' :-1,
'%-6' :-1,
'[<O>]' :0,
'' :0,
'>:/' :0,
'%-(' :-1,
'</3' :-1,
'(U)' :-1,
'=((' :-1,
'<~3' :-1,
'<\3' :-1,
'(brokenheart)' :-1,
':-(=)' :1,
':B' :0,
'(*^o^)(^o^*)' :0,
'}|{' :-1,
'=:)' :-1,
'()_()' :-1,
'(bug)' :-1,
'E=B' :-1,
"pq`#' ":0,
'):|' :0,
'3:(:)' :0,
'[O==O\=<(' :0,
'o^o-o{' :0,
'=;-(' :-1,
'(_)' :0,
'(")(")' :0,
'(")(")' :0,
"('')_('') ":0,
'-()()-' :0,
'' :0,
'(=^_^=)' :0,
"(='.') ":0,
'(O:3' :0,
'(")_(")' :0,
'o(_-\_' :0,
'()' :0,
'U.U' :0,
'(\_/)' :0,
'#-(' :0,
'(bus)' :0,
'[===]' :0,
':-)<////>' :0,
'()' :0,
'(_|_)' :0,
'(_!_)' :0,
'}i{' :0,
'})i({' :0,
'})U({' :0,
'' :0,
'`-----------`' :0,
'(call)' :0,
':-c' :0,
"~M' ":0,
'(p)' :0,
'|C|' :0,
'|P|' :0,
'o=' :0,
'-=' :0,
'~=' :0,
'~===|' :0,
'>(///)<' :0,
'P=\\' :0,
'((-_(-_-)_-))' :0,
'(^o)(^0^)(o^)' :0,
'(cash)' :0,
'(mo)' :0,
'($)' :0,
'|*-*|' :0,
">'o'< ":0,
'=^.^=' :0,
'>;3' :0,
',,,^..^,,,~' :0,
">'.'< ":0,
'(^-_-^)' :0,
'<^oo^>' :0,
'=^_^=' :0,
'(==)' :0,
'(=^^=)' :0,
'>^..^<' :0,
'(@)' :0,
'<^..^>' :0,
'^-.-^' :-1,
'(:@@@@@D' :-1,
'<0_/\_/\_' :-1,
'~o(:-)' :0,
'(O)' :1,
'(<._.>)' :0,
'|-{' :0,
'C|:-=' :0,
'()' :0,
':-@' :-1,
'\o/' :1,
'' :1,
'' :1,
'()' :1,
'*\O/*' :1,
'C=:-)' :0,
'(:=3' :0,
'~:>' :0,
'<)' :0,
'(*>' :0,
'8^' :0,
'-{:-]' :0,
':putnam:' :0,
'*<<<<=' :0,
'' :0,
'|_|' :0,
'^)_(^' :1,
'<{^-^}>' :1,
'(ci)' :0,
'=====~' :0,
':-.)' :1,
'(:)' :0,
'(clap)' :1,
'()//' :1,
'(o)' :0,
'<]:o){' :0,
':O)' :0,
'*:o)' :0,
'<|:^0|<' :0,
'*<:o)' :0,
'*<:^)' :0,
'*<:oP' :0,
'*<:oB' :0,
'(c:>*' :0,
'*<8-)X' :0,
'><*:oDX' :0,
'' :0,
'=:-)' :0,
'(C)' :0,
'C[_]' :0,
'~0)|' :0,
'(coffee)' :0,
':-{}' :0,
'' :0,
'?_?' :0,
'$:-)' :0,
'(;)(-_-)' :1,
'(co)' :0,
'_____' :0,
'|O-O|' :0,
'|:::|' :0,
'-----' :0,
'@/:^)' :0,
':-r' :0,
':-8(' :-1,
':^)' :-1,
'O.o' :-1,
':-Q' :-1,
':-/' :-1,
':-S' :-1,
':s' :-1,
':-$' :-1,
'(@_@)' :-1,
'=?' :-1,
",':( ":-1,
'O.o?' :-1,
':-??' :-1,
'(p_q)' :-1,
'\(_o)/' :-1,
'?:|' :-1,
'-.-?' :-1,
'(-?)' :-1,
'()' :-1,
'(-_-)' :-1,
':?' :-1,
':-?' :-1,
':???:' :-1,
'o_O' :-1,
'(??)' :-1,
'8-/' :-1,
'8/' :-1,
'B-)' :1,
'qB-)' :1,
'-D' :1,
'8=)' :1,
'B=)' :1,
'(cool)' :1,
':B)' :1,
'B)' :1,
'-<0oo' :0,
'3:-O' :0,
'3:O' :0,
'3:08' :0,
'<):-)' :1,
'}:-)' :1,
'<):)' :1,
'C):)' :1,
'(-:(3' :1,
'C):-)' :1,
'{:-)' :0,
')O{)|><' :0,
'V.v.V' :-1,
'V.^.' :0,
'(\/)!_!(\/)' :-1,
'' :-1,
'()_RED_(>' :0,
'())Crayola))>' :0,
'(_)' :0,
'%-)' :0,
'()' :0,
'>,=,-' :0,
':_(' :1,
':*(' :1,
'T_T' :1,
':((' :1,
":'( ":1,
';_;' :1,
'QQ' :1,
':..[' :1,
'T^T' :1,
"='( ":1,
'8:::(' :1,
'TT^TT' :1,
'TT_TT' :1,
'i_i' :1,
":'-C ":1,
';-;' :1,
':"-(' :1,
':~-(' :1,
'TT.TT' :1,
'(!_!)' :1,
'&.(..' :1,
'(ToT)' :1,
'(;_;)' :1,
":'-( ":1,
';(' :1,
'Y.Y' :1,
'T.T' :1,
':cry:' :1,
';=(' :1,
'(cry)' :1,
'(-__-)' :1,
'|_|' :0,
'C(_)' :0,
'|_P' :0,
'C(_)' :0,
'|_P' :0,
'~o)' :0,
'[_]P' :0,
'@:-)' :0,
'8:-)' :1,
':-@!' :0,
'X3' :1,
'n_n' :1,
'||' :0,
'@-|' :0,
'()' :0,
'o-)' :0,
'O-(' :-1,
'.)' :0,
'Q-)' :0,
'*-(' :0,
'>P-(' :0,
':/7)' :0,
':)-S=' :0,
'\:D/' :1,
'<(..<)' :0,
'(>..)>' :0,
'~(o.o)~' :0,
'(^_^)(^_^)' :0,
'v(*.*)^' :0,
'(~^.^)~' :0,
'(dance)' :0,
'\o/' :0,
'(.)' :0,
'^^)' :0,
'(o)' :0,
'(o)' :0,
'C8<]' :0,
'()' :0,
'Q:|' :0,
'8->' :-1,
'*-*' :-1,
'**' :-1,
'[*_*]' :-1,
'x_x' :-1,
'x.x' :-1,
'XP' :-1,
'8-#' :-1,
'(X_X)' :-1,
'(+_+)' :-1,
'-=,o' :-1,
'(#_)' :-1,
'>T_T' :-1,
'(u_u)' :-1,
'(==)' :-1,
'()' :-1,
'~(O)|' :0,
'3:*)' :0,
'(T_T)->' :-1,
'(_)' :-1,
'^(#)_' :-1,
'(<_>)' :-1,
'._.' :-1,
'-----' :-1,
'(._.)' :-1,
'c_*' :-1,
'(;)' :-1,
':-[' :-1,
'i-)' :0,
'()' :-1,
'>:)' :-1,
'(6)' :-1,
']:->' :-1,
'}:-)' :-1,
'()}:o)' :-1,
'}=^{|~' :-1,
'3:)' :-1,
'>:-)~' :-1,
'>;->' :-1,
'3:-)' :-1,
':evil:' :-1,
'(devil)' :-1,
':[' :-1,
':-[' :-1,
'>:->' :-1,
'[](*' :0,
'{>O' :0,
":-') ":0,
'/\"' :0,
'_..._' :0,
'=|:-)X' :0,
':-|' :-1,
':|' :-1,
':(&' :-1,
'=\"' :-1,
'Disappointe' :0,
'' :-1,
'DX' :-1,
'-__-' :-1,
'(*m)' :-1,
'/:(' :-1,
'%-}' :-1,
'd[-_-]b' :0,
'[:-}' :0,
'd^_^b' :0,
':-$' :0,
':-)-o' :0,
'O:v)>--o' :0,
':O?' :0,
':O/' :0,
':O$' :0,
':O)' :0,
'<[.,=.,]-' :0,
'<[~.~]>' :0,
':o3' :0,
'<*^)' :0,
'<*^)' :0,
':3-<' :0,
'/(^.^)\"' :0,
'(UxU)' :0,
'UU' :0,
'' :0,
'U)~' :0,
'' :0,
'' :0,
'8==3' :0,
'&===3' :0,
'(&)' :0,
'VV' :0,
'(>.<)' :0,
'[$(1)$]' :-1,
'===:-D' :0,
'(8)<=' :0,
':D))' :0,
'}:-(=' :1,
'(>:^F)' :1,
'^.=.^' :-1,
'<*,^^,--' :-1,
'I-)' :1,
'*DRINK*' :0,
'\%/' :0,
'=P~' :0,
':-P' :0,
':P' :1,
'*DROOLING*' :0,
':)_' :0,
':-B' :0,
'(**)' :0,
'~~~~\o/~~~~' :-1,
':*)' :-1,
':*)?' :-1,
'%-<I>' :-1,
':#)' :-1,
'(drunk)' :-1,
'o_O' :-1,
'_|V|_' :0,
'8()' :0,
'\_O<' :0,
':-F' :0,
'|-(' :-1,
'|(' :-1,
'|=(' :-1,
'p^b' :-1,
'8)' :-1,
'Oo!' :1,
'<:-|' :-1,
'<:-)' :-1,
'()))TNT)))-x' :0,
'' :1,
'p^_^q' :0,
'::--((' :0,
':g' :0,
':K' :0,
'()' :1,
'()' :1,
'(:-|' :1,
'~~~\8-O' :0,
'\/\/\/\,8-O' :0,
':~' :0,
'~:3' :0,
'\_/' :0,
"~MC'~ ":0,
'}.' :0,
'*<:-)-:--:' :0,
'' :0,
'@=)' :0,
'2:)' :0,
'?:-p' :0,
':-[]' :0,
'5:-)' :0,
'&:-)' :0,
':-$' :0,
':$' :0,
':-[' :0,
'^^"' :0,
'(#^.^#)' :0,
':oops:' :0,
'(*/*)' :0,
'(##)' :0,
'//_^' :0,
'T-T' :0,
'(//.^)' :0,
'(//_^)' :0,
'(//_-)' :0,
'c//_+.' :0,
"c//_^' ":0,
'c/_-*' :0,
'(-_\\\)' :0,
'//_T)o.' :0,
'd(//^)b' :0,
'\/O\/O\/' :0,
'(emo)' :0,
',_' :0,
'(///.-)' :0,
'' :1,
'(*m*)' :-1,
'(v)' :-1,
'(envy)' :-1,
'(@){' :0,
'((((((^_^;)' :0,
'>:3' :0,
'(.\|/.)' :-1,
'):D}' :-1,
':{)' :-1,
'>:~>' :-1,
'>:{)>' :-1,
']}:-)>' :-1,
'>-)' :0,
'>:)' :0,
']:)' :0,
':twisted:' :0,
'(grin)' :0,
'>:D' :-1,
'()' :-1,
'>=)' :0,
'/^^\!' :-1,
':-O' :1,
'(*-*)' :1,
':o' :1,
'(^O^)' :1,
'()' :1,
'#-)' :-1,
'||' :-1,
'(;?`)' :-1,
'STO' :-1,
'(((ToT)~~' :-1,
'_(*)' :-1,
'<>' :0,
'P-)' :0,
'b-)' :0,
'' :0,
'}=D' :0,
'-@--@-' :0,
':&' :-1,
'(6.6)' :0,
'(_)' :0,
'?:-)' :1,
'o,..,o' :0,
'^,..,^' :0,
'(0)' :0,
'=^O.O^=' :0,
'O<-<=' :0,
';~[' :0,
'' :0,
'(~)' :0,
'(yn)' :0,
'X=' :0,
'()))))-x' :0,
'}-(((*>' :0,
'<")))><' :0,
'><(((">' :0,
'<.{{{><' :0,
'{}{' :0,
'<><' :0,
'<((((><' :0,
"<('O')> ":0,
'<*)))<' :0,
'|>///^<' :0,
'>)##)' :0,
'()#))<<' :0,
"<')+++< ":0,
'(~)' :0,
'p#d' :0,
'i-=<***' :0,
"!.'v ":0,
'OZ~<' :0,
'(_)' :0,
'()' :0,
'()' :0,
'()' :0,
'()' :0,
';D' :1,
';-)' :0,
'(ff)' :0,
';3' :1,
'(fm)' :0,
'@>---' :0,
'@>--;--' :0,
'<-#' :0,
"@-'- ":0,
'(f)' :0,
'(flower)' :0,
'###' :0,
'0==I==,==I===' :1,
"D'; ":0,
'O-&-<' :1,
':-!' :0,
'()' :0,
'G:-)' :0,
'=:-H' :0,
'C:#' :0,
'---E' :0,
'o^o-o|_' :0,
'|:-<' :-1,
'%%-' :0,
'88-' :0,
'Vm~' :0,
':^{=' :1,
'E:/' :0,
'[:-|I' :0,
'[8-]' :0,
'()' :-1,
'()' :-1,
'()' :-1,
'()' :-1,
":'| ":0,
':pd:' :0,
':bq:' :0,
':bd:' :0,
'(`*)' :1,
'8-|' :-1,
'()' :-1,
'8)~~*' :0,
'8)' :0,
':(?)' :0,
':()' :0,
'[II]D' :-1,
'' :-1,
'' :-1,
':-(' :-1,
':(' :-1,
':o{' :-1,
':-(' :-1,
'=P' :-1,
'X[' :-1,
':-P' :-1,
'><' :-1,
'B/' :-1,
'>.<*' :-1,
'-_-*' :-1,
':-L' :-1,
'()' :0,
'(fubar)' :0,
'|-[#]' :-1,
'B-}' :0,
'(_)' :-1,
'*:*' :-1,
':-(*)' :0,
'qB]' :-1,
'@}:-)' :0,
'=:o' :-1,
'' :1,
'3>(' :-1,
'(D:-]' :0,
'@:i' :0,
'{@:)}' :0,
'4:-)' :1,
'd=P' :-1,
'(>")>' :0,
'<(")>' :0,
'(",)' :0,
'(boo)' :0,
'()' :0,
'((()))' :0,
'8[+]' :0,
'()' :0,
'(g)' :0,
';))' :0,
'*GIGGLING*' :0,
'(giggle)' :0,
'(chuckle)' :0,
'()' :0,
'>:o===Q<' :0,
'(x)' :0,
'8:^)' :0,
'(-_-)#' :0,
'~0(**)0~' :0,
'(;`)' :1,
'' :1,
'>:[' :1,
'\~/' :0,
'\_/' :0,
'/:':-1,
'-o-o-' :0,
'8-)' :1,
'()-()' :0,
'-@--@-' :0,
'\o-o/' :0,
'(-_q)' :0,
'8)' :1,
'B-)' :1,
'B)' :0,
'(^0_0^)' :0,
'' :1,
'(nah)' :0,
'(nnh)' :0,
':-{>' :0,
'):()-' :0,
'o/' :0,
'()' :0,
'' :1,
'(`)' :1,
'(ToT)/~~~' :0,
':8]' :0,
'%:O' :0,
'8:]' :0,
'|<:-)' :0,
'L:-)' :0,
'Q:-)' :0,
'oO:)&' :0,
'' :0,
'(~};)' :0,
'$_$' :-1,
'($v$)' :-1,
'$__$' :-1,
".'! ":-1,
':->' :1,
':D' :1,
'-D' :1,
':oP' :1,
'' :1,
'(-_' :-1,
'v(*.*)^' :0,
'(^o^)' :0,
':-!' :-1,
"l:[' ":0,
'[>#<]' :-1,
'(.(.).)' :0,
'>:(' :-1,
'^i^' :1,
'>I<' :1,
'^_^;' :-1,
'(____)' :0,
'(_|||_)' :0,
'S:~)' :0,
'$8()' :0,
'*8D' :0,
'((:D' :0,
'~~8-O' :0,
'@:-)' :0,
'#:-)' :0,
'~#:-(' :-1,
'?:-)' :1,
'%-.-%' :0,
"@.'v ":0,
'{:-{)}' :-1,
'L-:' :1,
'(||]' :0,
'(%)' :0,
'(:>-<' :0,
':-|><' :0,
'(handshake)' :0,
'&:-]' :1,
'=)' :1,
':-)' :1,
':)' :1,
'^.^' :1,
'^^' :1,
'(:' :1,
'|___|' :1,
'^-^' :1,
'8D' :1,
'(^_^)' :1,
'8^)' :1,
':-}' :1,
'!_!' :1,
':)))' :1,
'(happy)' :1,
'()' :1,
'' :1,
'' :1,
'B^)' :1,
'8-D' :1,
'BD' :1,
'B^D' :1,
'8^D' :1,
'' :1,
'*<|:o)' :1,
'()' :1,
':")' :0,
'|||)' :0,
'<~8)' :-1,
'>O<' :-1,
'q=)' :0,
'xd:)' :1,
'*<:)' :0,
'+(:-)' :0,
"*<.'v ":0,
"d.'v ":0,
'\,,/(>.<)\,,/' :0,
'(({..}))' :-1,
'(|:-)' :0,
'>:^(' :-1,
'0(o.o)0' :0,
'd(-_-)b' :0,
'[:-)' :0,
"q[-'.'-]p ":0,
'dL-_-b' :0,
'<3' :1,
'<u3' :1,
'S2' :1,
'' :1,
'-(`.)->' :1,
'(h)' :1,
'(l)' :1,
'(heart)' :1,
'./\..|..|....' :0,
'()' :-1,
'\,,/' :0,
'(heidy)' :0,
'o_o' :0,
'(o)' :0,
'()!!' :0,
'?:)#' :0,
'' :0,
'(_;)_)' :-1,
'(_|' :-1,
'|)' :-1,
'|_)' :-1,
'~~' :0,
'(h5)' :0,
'o/\o' :0,
'^_^/' :0,
'(*)(*)' :0,
'^y^-/|\--Y^' :0,
'o->' :0,
':-/' :0,
'(#]' :0,
'L.' :0,
'L.' :0,
'8-)' :-1,
'(_8^(|)' :0,
'(8-(1)' :0,
'(_8^(1)' :1,
'~(_8^(|)' :1,
'o--}' :0,
'o(^^o)(o^^)o' :1,
'}:)' :1,
'O_' :0,
'[_]' :0,
']:-:)' :0,
'(h)' :0,
'(;)' :0,
'(:)\/<' :0,
':)X' :0,
"(>'')><(''<) ":0,
'(((H)))' :0,
'{}' :0,
'({})' :0,
'(bear)' :0,
'(hug)' :0,
'()' :0,
'{*}' :0,
'd=()=b' :0,
'<(^.^<)' :0,
'(>^_^)><(^o^<)' :-1,
'<(*.*<)' :0,
':D<' :1,
'((()))' :1,
'{{{***}}}' :1,
'[.]' :0,
'~!~' :-1,
'%*@:-(' :-1,
':0' :0,
':-[]' :0,
':!!' :0,
'XD' :1,
'@-)' :1,
':^)' :0,
'X_X' :0,
'_\m/' :1,
'~oO>' :1,
'<OO' :1,
'<Oo*' :1,
'<><' :0,
'*-:)' :0,
':idea:' :0,
'*help' :0,
'*red+u' :0,
':!:' :1,
'O-S-<' :0,
'(@)' :0,
'(*_*)' :1,
'<3+<3' :1,
'(_)' :1,
':]' :1,
'(inlove)' :1,
'(love)' :1,
':-]' :1,
'._.' :-1,
'_/\,' :0,
':-S' :-1,
'(o_O)' :-1,
':7/' :-1,
':-|' :-1,
':-I' :-1,
'E_E' :-1,
':neutral:' :-1,
'**' :1,
'(*)=3' :1,
'()' :1,
'0:-)' :0,
'O:D' :1,
'(wm)' :0,
'?_?' :-1,
'%7<' :-1,
'(ip)' :0,
'^#(^' :0,
'(wasntme)' :0,
':<|' :0,
'(:-|K-' :1,
'.().' :0,
'8(>_<)8' :-1,
'8-)' :1,
'//o-o\\' :0,
'((*J*))' :0,
'.-' :0,
'X-p' :1,
'(jk)' :1,
'*JOKINGLY*' :-1,
':-]' :1,
'\m/<(^_^)>\m/' :-1,
'()/' :-1,
'o(^o^)o' :-1,
'()' :-1,
'(:-#' :1,
'c",)' :0,
'K:P' :0,
'X:-)' :0,
'\VVV/' :0,
'\$$$/' :0,
']:)|--<' :0,
'<(^.^)>' :0,
"<('.'<) ":0,
"(>'.')> ":0,
'<(^_^)>' :0,
"<('.')> ":0,
"<('-'<) ":0,
"(>'')> ":0,
'c(-_-c)' :0,
'<(^,..,^)>' :0,
'(^^)' :0,
':-)*' :0,
':-X' :0,
':-*' :0,
';-(!)' :0,
':*)' :0,
'8^*' :0,
':+' :0,
':P' :1,
':*' :0,
'X(*/*)x' :0,
'(3)' :0,
'(xo)' :0,
':-{}' :0,
'(^3^)' :0,
'(*^3^)/~' :0,
'(*^^)^*)' :0,
':=*' :0,
'(kiss)' :0,
'()`)' :0,
'(_X_)' :0,
'' :0,
'*KISSED*' :0,
':}{:' :0,
'*KISSING*' :0,
'(}{)' :0,
'(-}{-)' :0,
':**:' :0,
'(=^-^=)' :0,
'=^.^=' :1,
'=+=' :1,
':3' :1,
'=^w^=' :1,
'(=^--^=)' :1,
'(=^^=)' :1,
'[|]' :0,
'>>:-|' :0,
'.-=o=-.' :1,
'+<#^v' :0,
'+<||-)' :0,
'@(*o*)@' :0,
'' :0,
'' :0,
'' :0,
':*)O' :0,
'' :0,
'&0(80<' :0,
'<{::}>' :0,
'(::)<' :0,
'-.-' :-1,
'' :0,
'l8r)' :0,
':))' :1,
'XD' :1,
':L' :1,
":'D ":1,
'=^D' :1,
'>8-D' :1,
'(^_^)' :1,
'()' :1,
'-*)' :1,
':o' :1,
'' :1,
'' :1,
'=-D' :1,
'=D' :1,
'X-D' :1,
'(lol)' :1,
':lol:' :1,
':.-)' :1,
'({)' :0,
'()' :-1,
':^o' :-1,
':PdPdP' :-1,
':-9' :-1,
'(`)' :-1,
'#-)' :1,
'(i)' :0,
'(li)' :0,
'(Y)' :1,
':3' :0,
':-*' :-1,
':-#' :-1,
':-X' :-1,
':X' :-1,
':#' :-1,
':=x' :-1,
':=#' :-1,
':()' :0,
':-{}' :0,
'd-_-b' :0,
'd^_^b' :0,
'd(^_^)b' :0,
'o(^_^)o' :0,
'd(-\\\)b' :0,
'_\\//' :1,
'>-<' :-1,
'(.`.)' :-1,
'(**)' :-1,
'~~I==I>' :0,
'' :0,
'@---' :0,
':P@---' :0,
':~)' :0,
'(*)?(*)' :-1,
'>_>' :-1,
'<_<' :-1,
'>.>' :-1,
'\\(<.<|>.>)//' :-1,
'(_)' :-1,
'<o?o>' :-1,
'<*_*>' :-1,
'L-)' :-1,
':-{}' :0,
'<3' :1,
'~~' :1,
':x' :0,
'__.' :0,
'o@=<' :0,
'=/' :0,
'>=(' :0,
'>,<' :0,
'~:(' :0,
'>=[' :0,
'>}:-(' :0,
':U' :0,
')8^(' :0,
':!' :0,
">;-(' ":0,
'>_<' :0,
':x' :0,
':-x' :0,
':mad:' :0,
'(#)' :0,
':-.)' :0,
'{8-*' :1,
'*)' :1,
'<*:-)' :-1,
'(malthe)' :0,
'0-|-[' :0,
'@@@@:-)' :1,
'(@@@@):^)' :1,
'######:o)' :1,
'@@@:)' :1,
'(#-[' :0,
':-)(-:' :0,
'' :0,
'' :0,
'-----(_)-' :-1,
'-()_)()_)' :-1,
'(.!.)' :0,
'=:)' :0,
'Q>--|' :0,
'(d)' :0,
'|>--|' :0,
'(drink)' :0,
'>:-I' :0,
'@|-)' :0,
'(-_-)' :0,
'' :0,
'' :-1,
'@_@' :1,
'\m/' :0,
'lml' :0,
'lml_' :0,
'|:-[|]' :0,
'8(:-)' :0,
'o/<' :0,
'(o:v)' :0,
':p' :1,
':}' :-1,
'?8}' :-1,
'=)=' :1,
':D:' :1,
'(mm)' :0,
'(mp)' :0,
'^o^' :0,
'-:-)' :0,
"=.'v ":0,
'(mo)' :0,
'[*(1)*]' :0,
'$-)' :0,
':-$' :0,
':-($)' :0,
'O|-)' :0,
'+<:-|' :0,
'@(-_-)@' :0,
':(|)' :0,
"@('.')@ ":0,
'---' :0,
"@'o'@ ":0,
'@(^_^)@' :0,
'@(*_*)@' :0,
'()=' :0,
'(;_)' :0,
':E' :-1,
';..;' :-1,
'VVV' :-1,
'>:(><)' :-1,
'(_i_)' :0,
'(mooning)' :0,
'(|)' :0,
'o-7-o' :0,
'o--7o' :0,
':o&o>' :0,
'^v^v^' :0,
'~<>^>' :0,
'oO~' :0,
'<:3)~' :0,
'<:3)~~' :0,
'<:3)~~~' :0,
'8(:-)' :0,
'(~)' :0,
'(film)' :0,
'(movie)' :0,
'(m)' :0,
'cl_l' :0,
'[II]D' :0,
'(_)' :0,
'(flex)' :0,
'(muscle)' :0,
'' :1,
'(music)' :0,
':-{' :0,
':{' :0,
'={D' :0,
':{D' :0,
':{)' :0,
':-#|' :0,
':-3' :0,
':{|' :0,
':-:' :-1,
'(myspace)' :0,
':_:' :0,
':-SS' :0,
'(Z(:^P' :0,
'~,~' :0,
'_:^)' :0,
':3' :0,
'*:-)' :-1,
'@:-)' :-1,
'#:-)' :-1,
'=:-)' :0,
'(-)' :0,
'*8-I' :-1,
':-B' :-1,
'8-|' :-1,
'8-B' :-1,
':-=H' :-1,
'B-|' :-1,
'8|' :-1,
'B|' :-1,
'(nerd)' :-1,
'8=|' :-1,
'B=|' :-1,
'|-(:-)' :-1,
'[-_-]~' :0,
'Qx' :0,
'QK' :0,
'(j)' :0,
'(ninja)' :0,
'[+..]' :0,
'(nod)' :0,
'(?_?)' :-1,
'):-(' :-1,
'<:@0' :0,
'(:^(' :0,
'(:+)' :0,
':/\)' :0,
':v)' :0,
'>*(' :0,
'.^v' :0,
'%-(' :0,
'<2' :1,
'[-(' :-1,
'^:)^' :1,
'(8)' :0,
']:-)' :0,
'~=[,,_,,]:3' :0,
'[^._.^]' :0,
'||' :0,
'O_o' :0,
':-j' :0,
'?:-_]' :0,
'|:-{)~' :0,
'(-o-)' :-1,
':)]' :0,
'' :0,
'' :0,
'()' :0,
':-(' :-1,
'=X' :0,
'E:-)' :0,
'~#|__/~~\o/~' :0,
'^_^' :-1,
'.^_^.' :-1,
':-)))' :1,
'^o,o^' :0,
'-(*o*)-' :0,
'(^o^)' :0,
"--''--''-- ":0,
'-"-"-' :0,
'^(OvO)^' :0,
'' :0,
':v' :0,
'(:V)' :0,
'(:\/)' :0,
'(V)=|' :1,
'(>_<)' :-1,
'(_)' :0,
'8:(' :0,
'(panda)' :0,
'' :0,
'\(>o<)/' :-1,
'\\(<.<|>.>)//' :-1,
'(>-:-)-<' :0,
'(@.@)' :-1,
'{|:{)' :0,
'<:-P' :1,
'<:o)' :1,
'<o)' :1,
'(party)' :0,
'*<(:)' :0,
'<l:0' :0,
'*<(8)~/~<' :0,
'*<|8-P~' :0,
'(:V' :0,
':)>-' :1,
'(/|\)' :1,
'(^o^)y' :1,
'*p*' :1,
'(-)' :1,
'(/)' :0,
'<IIEEEEEED' :0,
'0))__)>' :0,
"('v') ":0,
'<(")' :0,
'<(^)' :0,
"<('') ":0,
'8>' :0,
'*-)' :-1,
':-/' :-1,
'XP' :-1,
'<:^]' :0,
'O<-<' :0,
'>:P' :0,
'-()' :0,
':?)' :0,
'(mp)' :0,
'(ph)' :0,
'(phone)' :0,
'((()))' :0,
'/_/_/_/_/' :0,
'\___/' :0,
'----|}' :0,
'--===[}' :0,
'(~_(]=--Z()' :0,
'=8)' :0,
'o()~' :0,
':@)' :0,
':(:)' :0,
"<('@')> ":0,
':=)' :0,
'<(^oo^)>' :0,
'^(*(oo)*)^' :0,
'()' :0,
'^..^__)~' :0,
'(oo)' :0,
'/***(^o^)***\"' :0,
"/~'v'~\' ":0,
'(v)' :0,
"^_^'' ":0,
'(o^-^o)' :0,
'<(:-)' :0,
'(__)' :0,
'(_)' :0,
'' :-1,
':---)' :0,
':-------[' :0,
'b)' :0,
'P)' :0,
';PX' :0,
':ar!' :0,
'R)' :0,
'-=,q' :0,
'<%)' :0,
'(pi)' :0,
'<|' :0,
'(pizza)' :0,
'(pl)' :0,
';T' :1,
'\/' :0,
'(+[__]:)' :1,
'(^^)' :1,
'(pu)' :0,
'O-G-<' :0,
'()' :0,
'' :0,
':-I' :0,
'(*)(*O)' :1,
'' :1,
'-[[]]--[()]-' :0,
'[|:-{O' :0,
'c|:-|' :0,
'()' :-1,
'(poolparty)' :0,
'(hrv)' :0,
'~@~' :-1,
'+O=-)' :0,
'+<:-)' :0,
';-?' :0,
':<' :-1,
'>:-[' :0,
':-\"' :0,
'\o/' :1,
'O/' :1,
'_/\_' :0,
"/\'s ":0,
'[-o<' :1,
'_/\_' :1,
'_|' :1,
'(*)' :1,
'' :1,
'+:-)' :0,
'(zilmer)' :0,
'\<><>/' :0,
'O(+>' :0,
'~<:-)' :0,
'\&&&/' :0,
':}' :0,
'@(*-*)@' :0,
'x{|:)' :0,
'(+[PSP]::)' :0,
'' :-1,
'*3' :-1,
':&' :0,
'(puking)' :0,
'(^:^)' :0,
'(~~)' :0,
'*|' :-1,
'(_)' :0,
'(punch)' :0,
'(o(o' :0,
'=(-_-' :0,
'0()=' :0,
'(o)=)`)' :0,
'()=)-)' :0,
'-:-/' :-1,
'UU' :0,
"Q('.'Q) ":0,
'()' :-1,
'C):-' :0,
'C):-' :0,
'C):-' :0,
'C):-O' :1,
'\%%%/' :0,
':?:' :0,
'>-=]' :0,
"('.') ":0,
'(")_(")' :0,
'(uu)' :0,
'8:3' :0,
'`=o=^o>' :0,
'CD:-)>' :0,
'~~:-(' :0,
'(rain)' :0,
'(london)' :0,
'(R)' :0,
'/:)' :0,
'd:o)' :0,
'=:7)~~' :0,
'=:7(~~' :0,
'(((((:-{=' :-1,
'(l)' :0,
'(k)' :0,
'(f)' :0,
'}---:o>' :0,
'o(^)o' :-1,
'~o)' :-1,
'>=D' :-1,
'?$?:-)' :1,
'(})' :1,
'/O' :0,
'(_)' :0,
'________' :0,
'*<l:o)>' :-1,
'([(' :0,
'[*.*]' :0,
':|]' :0,
':]' :0,
':]]' :0,
'[:]' :0,
'<(-_-)>' :0,
'~(o_o)~' :0,
'[:|]' :0,
'\m/(**)\m/' :0,
'\m/@_@\m/' :0,
'\m/>.<\m/' :0,
'\m/(><)\m/' :0,
'd(>_<)b' :0,
'\m/(>.<)\m/' :0,
'bd(OoO)bd' :0,
'<:-)<<|' :0,
'<===~~' :0,
'\w/^^,\w/' :0,
'>-D' :0,
'\m/' :0,
'\\m/(=o+)\m//' :0,
'(rock)' :0,
'\m/(*o*)\m/' :0,
'\m/d(^_^)b\m/' :0,
'8-|' :0,
'>>' :0,
'9_9' :0,
'@@' :0,
'c.c' :0,
':roll:' :0,
'' :0,
'=))' :1,
'(rotfl)' :1,
'(rofl)' :1,
'()' :1,
'7:-)' :0,
'\:)' :0,
'~:>' :0,
'^:3' :0,
'@)->-' :0,
'@~)~~~~' :0,
'@}->--' :0,
'@};-' :0,
"@~'~~~ ":0,
'@>-;--' :0,
'@-->---' :0,
'--{--@' :0,
'@>--' :0,
'@}-^--^--' :0,
'(@)->->->--' :0,
'@}-(' :0,
'<(*_*)>' :0,
'3:*>' :0,
'(;_)' :0,
'=()' :0,
'' :0,
'=(;)' :0,
'=(' :-1,
':-(' :-1,
':(' :-1,
'T.T' :-1,
'=[' :-1,
':c' :-1,
'D:' :-1,
'D=' :-1,
'Y_Y' :-1,
'v.v' :-1,
'\8^1' :-1,
'(<_>)' :-1,
'(/_\)' :-1,
'):' :-1,
'(_)' :-1,
':[' :-1,
':sad:' :-1,
':=(' :-1,
'(sad)' :-1,
'8-(' :-1,
'/:-)' :0,
';-)}<////>' :0,
'>>>>(:-)' :0,
'M:-)' :1,
'O7' :1,
':-{o' :0,
'*<]:{)' :1,
'*<(:-{)}' :1,
'*<:-)' :1,
'*<|:-{)}' :1,
'<|:)}' :1,
'0<[]:-)>>' :1,
'*-={:-)}}}>' :1,
'*<|:o)>' :1,
'<[]:o{|>' :1,
'*<[]:o{|>' :1,
':-7' :-1,
'^o)' :-1,
';s' :-1,
':S' :-1,
'D:' :-1,
':!' :-1,
'(;)' :-1,
'.()' :-1,
'()' :0,
'()' :-1,
'' :1,
'*!#*!^*&:-)' :-1,
'!:-)' :0,
'*s*' :0,
'8<' :0,
'c--I-I-I{' :-1,
'3#`' :-1,
'>-$' :-1,
'^:-/' :0,
':-@' :-1,
'..._[:]' :0,
'..._(:)-o' :0,
'O-)' :0,
'(:)-)' :0,
"\';./ ":0,
'' :0,
'()' :0,
';^!' :0,
':-*' :1,
'8==8' :-1,
'\000/' :0,
'(shake)' :1,
'9(x.x)9' :1,
'(x.x)9' :1,
'[-x' :-1,
'<(((">' :0,
'(^^^)' :0,
'~~~/\\~~~' :0,
'>---^-*<' :0,
'_/\____\0/__' :0,
'_/\_\o/_' :-1,
'=O' :-1,
'*SHOCKED*' :-1,
'o_o' :-1,
':-o' :-1,
'8-0' :-1,
'8^{}' :-1,
'(O_O)' :-1,
'8O' :-1,
':shock:' :-1,
'(**)' :-1,
'' :-1,
'=(.)=r' :0,
'()o*--' :0,
'()*' :0,
'' :0,
'^^' :-1,
':-V' :-1,
':\/' :-1,
'|----D' :0,
"`\('_')/` ":-1,
'\(_)/' :0,
'\_()_/' :0,
'(*^_^*)' :0,
'-_-' :0,
'(^^;)' :0,
'(#^.^#)' :0,
'(#/\#)' :0,
'(*)' :0,
'(-:|:-)' :0,
':-&' :-1,
'+o(' :-1,
'|-~b' :-1,
'(-__-)' :-1,
':-~)' :-1,
':->|' :-1,
':-Y' :0,
':-<' :0,
'8-}' :0,
'=P' :1,
'C(:' :0,
'(^o^)' :0,
':-o' :0,
'(o)~' :0,
']:' :0,
'O-\-<]:' :0,
'0-<-<):' :0,
'o{-<]:' :0,
'O[-<]:' :0,
'o<[^(' :0,
'o->-</:' :0,
'q=)-<--<|:' :0,
'O-/-<]:' :0,
':-/' :-1,
':-7' :-1,
':/' :-1,
'(.)' :-1,
'*(H-)' :0,
'=(^-^)' :0,
'8-X' :0,
'(skype)' :0,
'(ss)' :0,
'(^^)(o)' :0,
'(>.<)' :-1,
'-_-' :-1,
'-_-' :-1,
'(-.-)zzZZ' :-1,
'Z/' :-1,
'Z_Z' :-1,
'(~_~)^' :-1,
'(-_o)zzZ' :-1,
'O-(==<' :-1,
'<-.->' :-1,
'(--)zzz...' :-1,
'' :-1,
'|-)' :0,
'(>.<)' :0,
'u_u' :0,
'#)' :0,
'"8^y' :0,
'~_~' :0,
'(-_-)Zzz' :0,
'(Z.Z)' :0,
'I-)' :0,
'(snooze)' :0,
'I=)' :0,
"#(,'%/) ":0,
':-#' :0,
':-)' :1,
':)' :1,
'\_/' :1,
'[______]' :1,
':|)' :1,
'C:' :1,
'\\)' :1,
':A' :1,
':)' :1,
'=]' :1,
'\__/' :1,
'(*8' :1,
'I:(' :1,
'>-)' :1,
':^D' :1,
':]' :1,
':smile:' :1,
':=)' :1,
'(smile)' :1,
'()' :1,
':^J' :1,
'^^' :1,
'^&^' :1,
".'J ":1,
':-1' :0,
':-,' :0,
':^,' :0,
';^)' :0,
'(smirk)' :0,
'()' :1,
':-p~' :0,
':-d~' :0,
':-Q' :0,
':O\"' :0,
':-' :0,
':-?' :0,
':-d' :0,
':-G-' :0,
'(--)y-' :0,
'(())y-' :0,
'(smoke)' :0,
'(smoking)' :0,
'(ci)' :0,
'o()y' :0,
':-?' :0,
'(`)' :1,
':>' :-1,
'B|' :-1,
'(sn)' :0,
'@x' :0,
'_@/' :0,
'`@____' :0,
'@_v' :0,
'@_' :0,
'_@_v' :0,
'_@v' :0,
'~<:<<<<<>' :0,
'~~~~8}' :0,
'~>)' :0,
':-`|' :0,
':<)' :-1,
'(_' :0,
'|^O' :0,
'^o' :0,
'' :0,
'(:^)_)_)' :0,
'[l:^)' :0,
'(:-)()' :0,
'*|:^)(.)(...)' :0,
'(`)' :-1,
'(A`)' :-1,
'.`(><)`.' :-1,
'(so)' :0,
'(____)' :0,
'/:-)' :0,
'c]:{D' :0,
'' :0,
'?-(' :-1,
'=^{' :-1,
'>.<' :-1,
':-*' :-1,
':-6' :-1,
'(X^(*' :-1,
'=.=' :-1,
'[>==]' :0,
'0_o' :-1,
'|-=[O]=-|' :0,
':-M' :-1,
'=#' :-1,
':|' :-1,
':-|' :-1,
':=|' :-1,
'(speechless)' :-1,
'||||' :0,
'/\(00)/\"' :0,
'' :0,
'^;;^' :0,
'::::(' :0,
':-`' :0,
'>:-I' :0,
'===()' :0,
'__m_OO_m__' :0,
'<:' :0,
'' :0,
'(><)' :1,
'-_-' :1,
'(*)' :0,
'(star)' :0,
'*~*' :0,
'' :1,
'(;_)' :1,
'()' :1,
'%.)' :1,
'=-O' :0,
'(~);}' :0,
';@' :-1,
'||=||' :0,
'|:-|' :-1,
'' :0,
'/\"' :0,
'' :0,
'#:-)-{--<' :0,
'>-/-@' :0,
'O-[--<' :0,
':-)~' :1,
':-P' :1,
':P' :1,
'>:P' :1,
':-r' :1,
':pp' :1,
':(,)' :1,
'(:-p)' :1,
'' :1,
".'r ":1,
':razz:' :1,
':=P' :1,
'(tongueout)' :1,
'~/~' :1,
'$:-$' :0,
'>;D' :0,
'*STOP*' :0,
'(st)' :-1,
':|' :0,
".'T ":0,
'-.-' :-1,
'O=[O{|___|]=O' :0,
'@?@' :-1,
'[o].[o]' :-1,
'&;-P' :1,
'(sun)' :0,
'8-)' :0,
'B-)' :0,
'B-D' :0,
']-I' :0,
'B:-)' :0,
'8-|' :0,
'8|' :0,
'B-|' :0,
'B|' :0,
'8)' :0,
':cool:' :0,
'c-oo' :0,
'_\|/_' :1,
'(#)' :1,
'((o))' :1,
':o' :0,
':-O' :0,
'*SURPRISED*' :0,
':O' :0,
'{:o' :0,
'(:)o)' :1,
'O-' :0,
':-()' :0,
'=0' :0,
'(*.*)' :0,
'l8^O' :0,
'****' :0,
'' :0,
'*_*' :0,
':eek:' :0,
':=o' :0,
'(surprised)' :0,
'*.*' :0,
'(O.O)' :0,
'=^o' :0,
'=^0' :0,
'' :-1,
'' :-1,
'' :-1,
':#' :-1,
'>:-@!' :-1,
'(swear)' :-1,
'`:-)' :0,
'(:|' :0,
'(sweat)' :0,
'8-)' :0,
'__/\o_' :0,
'B-)-[<' :0,
'x_O' :-1,
'/________|___|' :0,
'oxx:{}:::::::>' :0,
'cxxx{}:::::::>' :0,
'0]xxxx]====>' :0,
'<=======|==o' :0,
'(>_)(_<)' :0,
'---(|||]==[]' :0,
'+=>-' :0,
'/(..)' :0,
'(>o<)' :0,
'=;' :0,
':^y' :-1,
':y' :-1,
'(talk)' :-1,
'(____)' :0,
'|"""\-=' :0,
'(____)' :0,
'>8-O-(&)' :1,
'()' :1,
'(tuari)' :0,
'\_/?' :0,
'C(_)~' :0,
"C(_)~' ":0,
':p' :1,
'B^P' :-1,
':^P' :-1,
'8^P' :-1,
':O)' :0,
'()' :0,
'(t)' :0,
'(((((^_^)' :0,
'-(:)(0)=8' :0,
'>[I' :0,
'ixxxxxi' :0,
'|B-)' :0,
'-:}' :0,
'8=:-K' :0,
':-?' :0,
'*-)' :0,
':?' :0,
':=?' :0,
'(think)' :0,
'(*_)*' :0,
'(n)' :0,
"q('-')p ":0,
':-q' :0,
'(no)' :0,
'(y)' :0,
"d'-' ":0,
"d'-'b ":0,
':-bd' :0,
'(^-^)b' :0,
'd-(^.^)z' :0,
'(ok)' :0,
'(yes)' :0,
':-)<////>' :0,
'|-(o)-|' :0,
'(-o-)' :0,
'|o|' :0,
':-T' :1,
'[]---|<O---[]' :0,
'(o)' :0,
'(time)' :0,
'(clock)' :0,
':-t' :0,
'-<:-(' :0,
'(:|' :0,
'*TIRED*' :0,
'=_=' :0,
'%-|' :0,
'%-/' :0,
'(z_z~.)' :0,
'()' :0,
'(=_=)' :0,
'(%]:D' :1,
'0000(0)(0)0000' :0,
'.oooO' :0,
'Oooo.' :0,
'(toivo)' :0,
".'w ":0,
'8-;)' :0,
':-J' :0,
':j' :0,
':-&' :0,
':-a' :0,
'(tmi)' :0,
'[|:)' :0,
'#:o\:o/:o\:o/:o||' :0,
"=') ":-1,
'{(:-)' :0,
'}:-(' :0,
'{:-)' :0,
'-HHHH' :0,
'[..]' :0,
'>~<' :0,
'>:-|' :0,
':<()' :0,
'---(o__)o' :-1,
'(>_<)>' :-1,
'(^_^;)' :-1,
'<.<' :-1,
'' :0,
'oo---oo-Bo' :0,
'-=iii=<()' :1,
'(_)' :0,
'O>-O>-|-<O-<O' :0,
'X:-|' :0,
'@=)' :0,
'@:-v' :0,
'<:>==' :0,
'mm' :0,
'' :0,
'=8>-()<' :0,
'(tu)' :1,
':(' :-1,
'/Y\"' :0,
':-)8---' :0,
':-)8>' :0,
'.-=-.' :0,
'(o|o)' :0,
'(um)' :0,
'(---,' :0,
'q;|' :0,
'x:-/' :-1,
'=l:-)=' :0,
'=):-)>' :0,
':-\"' :-1,
':\"' :-1,
'/:-|' :-1,
':<' :-1,
'|:-)' :0,
'|:' :-1,
'' :-1,
'**==' :1,
">->' ":-1,
':/' :-1,
'8-\"' :-1,
'>.<' :-1,
'}:(' :-1,
'>:*' :-1,
'D:<' :-1,
'>=P' :-1,
'>-:O' :-1,
'--"' :-1,
'.-.' :0,
'P:' :1,
':-E' :0,
"(';.;') ":0,
'@,.,@' :0,
'*,..,*' :0,
'-,..,-' :0,
':-{' :0,
':f' :0,
',..,' :0,
'(o,..,o)' :0,
'(=,..,=)' :0,
':-[' :0,
':(=' :0,
'8-E' :0,
'>:-E' :0,
'>8-E' :0,
'>:-[' :0,
'8-{' :0,
'>8-{' :0,
':-[' :0,
':[' :0,
'^,..,^' :0,
'^,..,^' :0,
'~;;~' :0,
'(^-^:)' :1,
':-[' :0,
'%*}' :-1,
'=D' :1,
':-))' :1,
':-((' :-1,
'(o^_^)o' :1,
'v(^_^)v' :1,
'()' :1,
'8<' :0,
'](-[3' :0,
'(o\_!_/o)' :-1,
'(o^)/(^o)' :0,
'' :0,
'ixxxxxxx' :0,
':O=' :-1,
':-C..' :-1,
"(>'.')># ":-1,
"(>'_')># ":-1,
'#<(0.0<)' :-1,
'(o*)' :0,
'(wait)' :0,
'(((((((`)' :0,
'(_)' :0,
':->X==|' :0,
'_()' :0,
':-w' :1,
':3=' :0,
'(:{C)' :0,
':-<' :0,
'(:3=' :0,
'._)' :1,
'__/\o_' :0,
':-h' :0,
'(wave)' :0,
'(hi)' :0,
'(bye)' :0,
'~~c___' :0,
':-)--' :-1,
'(~`)' :-1,
';w;' :-1,
'(;`)' :-1,
'(><)' :-1,
':-P' :0,
'-_-' :0,
':-1' :0,
'(_)' :0,
'(_)' :0,
'd-:' :0,
'#:-S' :0,
'(whew)' :0,
":'( ":-1,
":'-( ":-1,
'*WHINING*' :-1,
'(`)' :-1,
':-"' :0,
".'Y ":0,
'()' :0,
'()' :0,
'(w)' :-1,
'' :0,
'())=(' :0,
';p' :1,
';-P' :1,
';^)' :1,
'(`_^)' :1,
',-)' :1,
'(^_~)' :1,
'9-)' :1,
'6-)' :1,
'i)' :1,
'!)' :1,
';-)' :1,
';)' :1,
'~_^' :1,
';()' :1,
':wink:' :1,
';=)' :1,
'(wink)' :1,
'' :1,
'(^)' :1,
'!-)' :1,
'(-!' :1,
'^_^a' :-1,
'' :-1,
'<):^/' :-1,
'___' :-1,
'<|:~,' :-1,
'I8${}' :-1,
'8<:-)' :-1,
'<{{{};->~' :-1,
'<*(:-?' :-1,
'(-).*' :-1,
'{0-|<[' :0,
'o>-<|=' :0,
'o.o?' :1,
':^)' :1,
'(wonder)' :1,
'||' :0,
'(wo)' :0,
':-S' :-1,
'(;)' :-1,
'>w<' :-1,
':S' :-1,
':=S' :-1,
'(worry)' :-1,
'' :-1,
'(`)' :-1,
'()' :-1,
'()' :0,
'(_;)' :0,
'()' :0,
'(xx)' :0,
'[x]' :0,
'_/)' :0,
'|-O' :-1,
'(:|' :-1,
".'U ":-1,
'(yawn)' :-1,
'(;`)' :-1,
'*\o/*' :0,
'>:O' :-1,
'=^Y' :-1,
':-(0)' :-1,
':(*)' :-1,
'(*O)' :-1,
'(__)' :0,
'(%)' :0,
'\(o/' :0,
'<(-_-)>' :0,
'<(-.-)>' :0,
':-0>' :0,
'()' :1,
':#' :0,
'F(x_x)F' :-1,
'8-#' :-1,
'[-]' :-1,
'B-)===>' :0
}
















